# Generated by Django 4.2.2 on 2023-08-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tag_alter_user_is_active_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
