# Generated by Django 4.2.2 on 2023-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000000)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('in_the_main_page', models.BooleanField(blank=True)),
                ('tags', models.ManyToManyField(to='store.tag')),
            ],
        ),
    ]
