# Generated by Django 4.2.2 on 2023-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_the_main_page',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
