# Generated by Django 3.0.7 on 2023-10-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('shipping', 'shipping'), ('delivered', 'delivered')], default='pending', max_length=1000),
        ),
    ]
